### PR TITLE
Repair to the post-pre-conference workshops stuff.

### PR DESCRIPTION
**Pull request by russel**
s/6/5/ in relevant two places.

Generated pages now match the ones in the Website repository.

### CODE REVIEW

**Comment by russel** [comment]
#98 replicates this change. Perhaps both should be rejected in favour of calculating the number? Excpt that how often is there a session after the pre-conference workshops?

**Comment by FelixPetriconi** [comment]
I propose to close this PR and we should find a generic solution for next year.

**Comment by russel** [comment]
I think we should either:

1. Apply this change now and then look to do the "no magic numbers" version for 2020; or
2. Put in place the "no magic numbers" version now.

My reasoning is that we need this code to generate the right AsciiDoc now rather later.

It's 5 mins effort for 2, so let me prepare a merge request for it. Given I already have the explicit literal change in my master rather than a feature branch, this merge request will appear anyway even in that.

**Comment by FelixPetriconi** [comment]
If it that easy, then I would go for 2.

**Comment by russel** [comment]
This should remove the magic numbers, tidy things up, and replicate the current pages. It also includes the changes proposed in #99 which can perhaps be declined now.

**Pull request merged**
