### PR TITLE
Consolidate the full day worksop day

### PR DESCRIPTION
**Pull request by FelixPetriconi**

### CODE REVIEW

**Comment by FelixPetriconi** [comment]
I had to change the constraints to proposal table to allow the room old_vic. I am not sure just right now, what else would be necessary.

**Comment by russel** [comment]
The problem here is the data model as it was when the SQLite database was created and the data model for the 2020 version. To put something in 'Old Vic' this year it has to be scheduled in 'Bristol 1' and then manually "relocated" in the page generation script. This is the main downside of not allowing schema migrations during a year. However, I suspect we now have enough of the rooms in the data model not to have this problem in the future.

**Comment by russel** [comment]
Has the database scheme been altered, rooms should be an enum, but it looks like a varchar now, which breaks the entire SQLAlchemy set up of the Python application.

**Comment by FelixPetriconi** [comment]
Your first comment was quite frightening to me ;-)

I just compared a backup with the current db and it is still a VARCHAR(13). Puh.

What I just did, was the following command:

```sql
create table proposal2
(
  id           INTEGER      not null
    primary key,
  proposer_id  INTEGER
    references user,
  title        VARCHAR(150) not null,
  summary      TEXT         not null,
  session_type VARCHAR(15)  not null,
  audience     VARCHAR(12)  not null,
  keywords     VARCHAR(100),
  no_video     BOOLEAN      not null,
  notes        TEXT,
  constraints  TEXT,
  status       VARCHAR(12)  not null,
  day          VARCHAR(9),
  session      VARCHAR(9),
  quickie_slot VARCHAR(6),
  room         VARCHAR(13),
  check (no_video IN (0, 1)),
  constraint conferenceday
  check (day IN ('workshops', 'day_1', 'day_2', 'day_3', 'day_4')),
  constraint proposalstate
  check (status IN ('submitted', 'accepted', 'acknowledged', 'rejected', 'backup', 'withdrawn')),
  constraint quickieslot
  check (quickie_slot IN ('slot_1', 'slot_2', 'slot_3', 'slot_4')),
  constraint room
  check (room IN
         ('bristol_suite', 'bristol_1', 'bristol_2', 'bristol_3', 'empire', 'great_britain', 'wallace', 'concorde', 'old_vic')),
  constraint sessionaudience
  check (audience IN ('beginner', 'intermediate', 'expert', 'all')),
  constraint sessionslot
  check (session IN ('session_1', 'session_2', 'session_3')),
  constraint sessiontype
  check (session_type IN ('fulldayworkshop', 'session', 'workshop', 'longworkshop', 'quickie', 'keynote'))
);

insert into proposal2 (id, proposer_id, title, summary, session_type, audience, keywords, no_video, notes, constraints, status, day, session, quickie_slot, room)
  select id, proposer_id, title, summary, session_type, audience, keywords, no_video, notes, constraints, status, day, session, quickie_slot, room from main.proposal;

drop table main.proposal;

alter table proposal2 rename to proposal;
```

I thought about misusing a room for an other one, but I did not like this, since two are working now on the code and such hidden features are error prone from my point of view.

So that was my open question, what else needs to be changes in the Python code to reflect this addition constraint value?

**Comment by russel** [comment]
I have to admit I know zero SQL, but this is generally not a problem when using SQLAlchemy with Python since it takes care of it all. Manual schema changes are generally a really bad idea in the Python/SQLAlchemy set up, there is a way of doing schema migrations that keeps all the management information in place: manual schema changes break the system – though this change may just about have got away with it.

I had lived with  "don't change the schema, but hack rooms" because it only affected the pre-conference workshops and over time as we find out which rooms can be used, the problem goes away.

I think though we may be in an OK state, despite the potential problem of not keeping the schema migration data for the SQLAlchemy infrastructure.

It appears though the meeting after the pre-conference workshops has gone missing fr the Python code.

**Pull request merged**
